class GeographicInfo():
    state_abbreviations = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA",
                           "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
                           "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
                           "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
                           "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

    state_names = ["ALABAMA", "ALASKA", "ARIZONA", "ARKANSAS", "CALIFORNIA", "COLORADO",
                   "CONNECTICUT", "DELAWARE", "FLORIDA", "GEORGIA", "HAWAII", "IDAHO",
                   "ILLINOIS", "INDIANA", "IOWA", "KANSAS", "KENTUCKY", "LOUISANA", "MAINE",
                   "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI",
                   "MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY",
                   "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO",
                   "OKLAHOMA", "OREGON", "PENNSYLVANIA", "RHODE ISLAND", "SOUTH CAROLINA",
                   "SOUTH DAKOTA", "TENNESSEE", "TEXAS", "UTAH", "VERMONT", "VIRGINIA", "WASHINGTON",
                   "WEST VIRGINIA", "WISCONSIN", "WYOMING"]

    nky_zip = ["41016", "41011", "41017", "41018", "41015", "41051", "41063", "41094", "41030",
               "41033", "41092", "41091", "41094", "41042", "41005", "41048", "41080", "41076",
               "41001", "41007", "41059", "41071", "41073", "41074", "41075"]

    ky_city_list = ["Adairville", "Albany", "Alexandria", "Allen", "Allensville", "Anchorage",
                    "Arlington",
                    "Ashland",
                    "Auburn",
                    "Audubon Park",
                    "Augusta",
                    "Bancroft",
                    "Barbourmeade",
                    "Barbourville",
                    "Bardstown",
                    "Bardwell",
                    "Barlow",
                    "Beattyville",
                    "Beaver Dam",
                    "Bedford",
                    "Beechwood Village",
                    "Bellefonte",
                    "Bellemeade",
                    "Bellevue",
                    "Bellewood",
                    "Benham",
                    "Benton",
                    "Berea",
                    "Berry",
                    "Blackey",
                    "Blaine",
                    "Blandville",
                    "Bloomfield",
                    "Blue Ridge Manor",
                    "Bonnieville",
                    "Booneville",
                    "Bowling Green",
                    "Bradfordsville",
                    "Brandenburg",
                    "Bremen",
                    "Briarwood",
                    "Brodhead",
                    "Broeck Pointe",
                    "Bromley",
                    "Brooksville",
                    "Brownsboro Farm",
                    "Brownsboro Village",
                    "Brownsville",
                    "Buckhorn",
                    "Burgin",
                    "Burkesville",
                    "Burnside",
                    "Butler",
                    "Cadiz",
                    "Calhoun",
                    "California",
                    "Calvert City",
                    "Camargo",
                    "Cambridge",
                    "Campbellsburg",
                    "Campbellsville",
                    "Campton",
                    "Caneyville",
                    "Carlisle",
                    "Carrollton",
                    "Carrsville",
                    "Catlettsburg",
                    "Cave City",
                    "Centertown",
                    "Central City",
                    "Clarkson",
                    "Clay",
                    "Clay City",
                    "Clinton",
                    "Cloverport",
                    "Coal Run Village",
                    "Cold Spring",
                    "Coldstream",
                    "Columbia",
                    "Columbus",
                    "Concord",
                    "Corbin",
                    "Corinth",
                    "Corydon",
                    "Covington",
                    "Crab Orchard",
                    "Creekside",
                    "Crescent Springs",
                    "Crestview",
                    "Crestview Hills",
                    "Crestwood",
                    "Crittenden",
                    "Crofton",
                    "Crossgate",
                    "Cumberland",
                    "Cynthiana",
                    "Danville",
                    "Dawson Springs",
                    "Dayton",
                    "Dixon",
                    "Douglass Hills",
                    "Dover",
                    "Drakesboro",
                    "Druid Hills",
                    "Dry Ridge",
                    "Earlington",
                    "Eddyville",
                    "Edgewood",
                    "Edmonton",
                    "Ekron",
                    "Elizabethtown",
                    "Elkhorn City",
                    "Elkton",
                    "Elsmere",
                    "Eminence",
                    "Erlanger",
                    "Eubank",
                    "Evarts",
                    "Ewing",
                    "Fairfield",
                    "Fairview",
                    "Falmouth",
                    "Ferguson",
                    "Fincastle",
                    "Flatwoods",
                    "Fleming-Neon",
                    "Flemingsburg",
                    "Florence",
                    "Fordsville",
                    "Forest Hills",
                    "Fort Mitchell",
                    "Fort Thomas",
                    "Fort Wright",
                    "Fountain Run",
                    "Fox Chase",
                    "Frankfort",
                    "Franklin",
                    "Fredonia",
                    "Frenchburg",
                    "Fulton",
                    "Gamaliel",
                    "Georgetown",
                    "Germantown",
                    "Ghent",
                    "Glasgow",
                    "Glencoe",
                    "Glenview",
                    "Glenview Hills",
                    "Glenview Manor",
                    "Goose Creek",
                    "Goshen",
                    "Grand Rivers",
                    "Gratz",
                    "Graymoor-Devondale",
                    "Grayson",
                    "Green Spring",
                    "Greensburg",
                    "Greenup",
                    "Greenville",
                    "Guthrie",
                    "Hanson",
                    "Hardin",
                    "Hardinsburg",
                    "Harlan",
                    "Harrodsburg",
                    "Hartford",
                    "Hawesville",
                    "Hazard",
                    "Hazel",
                    "Hebron Estates",
                    "Henderson",
                    "Heritage Creek",
                    "Hickman",
                    "Hickory Hill",
                    "Highland Heights",
                    "Hills and Dales",
                    "Hillview",
                    "Hindman",
                    "Hodgenville",
                    "Hollow Creek",
                    "Hollyvilla",
                    "Hopkinsville",
                    "Horse Cave",
                    "Houston Acres",
                    "Hunters Hollow",
                    "Hurstbourne",
                    "Hurstbourne Acres",
                    "Hustonville",
                    "Hyden",
                    "Independence",
                    "Indian Hills",
                    "Inez",
                    "Irvine",
                    "Irvington",
                    "Island",
                    "Jackson",
                    "Jamestown",
                    "Jeffersontown",
                    "Jeffersonville",
                    "Jenkins",
                    "Junction City",
                    "Keene",
                    "Kenton Vale",
                    "Kevil",
                    "Kingsley",
                    "Kuttawa",
                    "LaCenter",
                    "LaFayette",
                    "La Grange",
                    "Lakeside Park",
                    "Lakeview Heights",
                    "Lancaster",
                    "Langdon Place",
                    "Lawrenceburg",
                    "Lebanon",
                    "Lebanon Junction",
                    "Leitchfield",
                    "Lewisburg",
                    "Lewisport",
                    "Lexington",
                    "Liberty",
                    "Lincolnshire",
                    "Livermore",
                    "Livingston",
                    "London",
                    "Loretto",
                    "Louisa",
                    "Louisville",
                    "Loyall",
                    "Ludlow",
                    "Lynch",
                    "Lyndon",
                    "Lynnview",
                    "Mackville",
                    "Madisonville",
                    "Manchester",
                    "Manor Creek",
                    "Marion",
                    "Martin",
                    "Maryhill Estates",
                    "Mayfield",
                    "Maysville",
                    "McHenry",
                    "McKee",
                    "Meadow Vale",
                    "Meadowbrook Farm",
                    "Meadowview Estates",
                    "Melbourne",
                    "Mentor",
                    "Middlesboro",
                    "Middletown",
                    "Midway",
                    "Millersburg",
                    "Milton",
                    "Mockingbird Valley",
                    "Monterey",
                    "Monticello",
                    "Moorland",
                    "Morehead",
                    "Morganfield",
                    "Morgantown",
                    "Mortons Gap",
                    "Mount Olivet",
                    "Mt. Sterling",
                    "Mount Vernon",
                    "Mount Washington",
                    "Muldraugh",
                    "Munfordville",
                    "Murray",
                    "Murray Hill",
                    "Nebo",
                    "New Castle",
                    "New Haven",
                    "Newport",
                    "Nicholasville",
                    "Norbourne Estates",
                    "North Middletown",
                    "Northfield",
                    "Nortonville",
                    "Norwood",
                    "Oak Grove",
                    "Oakland",
                    "Old Brownsboro Place",
                    "Olive Hill",
                    "Orchard Grass Hills",
                    "Owensboro",
                    "Owenton",
                    "Owingsville",
                    "Paducah",
                    "Paintsville",
                    "Paris",
                    "Park City",
                    "Park Hills",
                    "Parkway Village",
                    "Pembroke",
                    "Perryville",
                    "Pewee Valley",
                    "Pikeville",
                    "Pineville",
                    "Pioneer Village",
                    "Pippa Passes",
                    "Plantation",
                    "Pleasureville",
                    "Plum Springs",
                    "Poplar Hills",
                    "Powderly",
                    "Prestonsburg",
                    "Prestonville",
                    "Princeton",
                    "Prospect",
                    "Providence",
                    "Raceland",
                    "Radcliff",
                    "Ravenna",
                    "Raywick",
                    "Richlawn",
                    "Richmond",
                    "River Bluff",
                    "Riverwood",
                    "Robards",
                    "Robinswood",
                    "Rochester",
                    "Rockport",
                    "Rolling Fields",
                    "Rolling Hills",
                    "Russell",
                    "Russell Springs",
                    "Russellville",
                    "Ryland Heights",
                    "Sacramento",
                    "Sadieville",
                    "St. Charles",
                    "St. Mary",
                    "St. Matthews",
                    "St. Regis Park",
                    "Salem",
                    "Salt Lick",
                    "Salyersville",
                    "Sanders",
                    "Sandy Hook",
                    "Sardis",
                    "Science Hill",
                    "Scottsville",
                    "Sebree",
                    "Seneca Gardens",
                    "Sharpsburg",
                    "Shelbyville",
                    "Shepherdsville",
                    "Shively",
                    "Silver Grove",
                    "Simpsonville",
                    "Slaughters",
                    "Smithfield",
                    "Smithland",
                    "Smiths Grove",
                    "Somerset",
                    "Sonora",
                    "South Carrollton",
                    "South Park View",
                    "South Shore",
                    "Southgate",
                    "Sparta",
                    "Spring Mill",
                    "Spring Valley",
                    "Springfield",
                    "Stamping Ground",
                    "Stanford",
                    "Stanton",
                    "Strathmoor Manor",
                    "Strathmoor Village",
                    "Sturgis",
                    "Sycamore",
                    "Taylor Mill",
                    "Taylorsville",
                    "Ten Broeck",
                    "Thornhill",
                    "Tompkinsville",
                    "Trenton",
                    "Union",
                    "Uniontown",
                    "Upton",
                    "Vanceburg",
                    "Versailles",
                    "Vicco",
                    "Villa Hills",
                    "Vine Grove",
                    "Wallins Creek",
                    "Walton",
                    "Warfield",
                    "Warsaw",
                    "Water Valley",
                    "Watterson Park",
                    "Waverly",
                    "Wayland",
                    "Wellington",
                    "West Buechel",
                    "West Liberty",
                    "West Point",
                    "Westwood",
                    "Wheatcroft",
                    "Wheelwright",
                    "White Plains",
                    "Whitesburg",
                    "Whitesville",
                    "Wickliffe",
                    "Wilder",
                    "Wildwood",
                    "Williamsburg",
                    "Williamstown",
                    "Willisburg",
                    "Wilmore",
                    "Winchester",
                    "Winding Falls",
                    "Windy Hills",
                    "Wingo",
                    "Woodburn",
                    "Woodbury",
                    "Woodland Hills",
                    "Woodlawn",
                    "Woodlawn Park",
                    "Worthington",
                    "Worthington Hills",
                    "Worthville",
                    "Wurtland"]

    @staticmethod
    def get_cities():
        return GeographicInfo.ky_city_list

    @staticmethod
    def get_zips():
        return GeographicInfo.nky_zip

    @staticmethod
    def make_keywords():
        return ["charity"]
        # # A loops that repeatably asks the user for input until he/she inputs "no"
        # keyword_list = []
        # while True:
        #     user_input = raw_input("Enter a Keyword, type q to end: ")
        #     if user_input != 'q':
        #         keyword_list.append(user_input)
        #     else:
        #         break
        # return keyword_list
